apiVersion: apps/v1
kind: Deployment
metadata:
  name: bureaudesk-notification-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bureaudesk-notification-service
  template:
    metadata:
      labels:
        app: bureaudesk-notification-service
    spec:
      containers:
        - name: bureaudesk-notification-service
          image: abhijithunni/bureaudesk-notification-service:latest
          ports:
            - containerPort: 3007
          envFrom:
            - configMapRef:
                name: notification-config
---
apiVersion: v1
kind: Service
metadata:
  name: bureaudesk-notification-service
spec:
  selector:
    app: bureaudesk-notification-service
  ports:
    - protocol: TCP
      port: 3007
      targetPort: 3007
